// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Jafouan.Entities.Entities
{
    public partial class tbClientes
    {
        public tbClientes()
        {
            tbFacturas = new HashSet<tbFacturas>();
        }

        public int clie_Id { get; set; }
        public string clie_Nombres { get; set; }
        public string clie_ApellIdos { get; set; }
        public string clie_Identidad { get; set; }
        public DateTime clie_FechaNacimiento { get; set; }
        public string clie_Sexo { get; set; }
        public int estc_Id { get; set; }
        public string clie_Telefeno { get; set; }
        public string muni_Id { get; set; }
        public string clie_Direccion { get; set; }
        public bool? clie_Estado { get; set; }
        public int clie_UserCrea { get; set; }
        public DateTime clie_FechaCreacion { get; set; }
        public int? clie_UserModifica { get; set; }
        public DateTime? clie_FechaModificacion { get; set; }

        public virtual tbUsuarios clie_UserCreaNavigation { get; set; }
        public virtual tbUsuarios clie_UserModificaNavigation { get; set; }
        public virtual tbEstadosCiviles estc { get; set; }
        public virtual tbMunicipios muni { get; set; }
        public virtual ICollection<tbFacturas> tbFacturas { get; set; }
    }
}