// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Jafouan.Entities.Entities
{
    public partial class tbFacturaDetalles
    {
        public int fade_Id { get; set; }
        public int fact_Id { get; set; }
        public int pren_Id { get; set; }
        public int fade_Cantidad { get; set; }
        public decimal fade_Total { get; set; }
        public int? fade_UserCrea { get; set; }
        public DateTime? fade_FechaCreacion { get; set; }
        public int? fade_UserModificacion { get; set; }
        public DateTime? fade_FechaModificacion { get; set; }
        public bool? fade_Estado { get; set; }

        public virtual tbFacturas fact { get; set; }
        public virtual tbUsuarios fade_UserCreaNavigation { get; set; }
        public virtual tbUsuarios fade_UserModificacionNavigation { get; set; }
        public virtual tbPrendas pren { get; set; }
    }
}