// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Jafouan.Entities.Entities
{
    public partial class tbFacturas
    {
        public tbFacturas()
        {
            tbFacturaDetalles = new HashSet<tbFacturaDetalles>();
        }

        public int fact_Id { get; set; }
        public int clie_Id { get; set; }
        public int empl_Id { get; set; }
        public DateTime fact_Fecha { get; set; }
        public int sucu_Id { get; set; }
        public int meto_Id { get; set; }
        public int? fact_UserCrea { get; set; }
        public DateTime? fact_FechaCreacion { get; set; }
        public int? fact_UserModificacion { get; set; }
        public DateTime? fact_FechaModificacion { get; set; }

        public virtual tbClientes clie { get; set; }
        public virtual tbEmpleados empl { get; set; }
        public virtual tbUsuarios fact_UserCreaNavigation { get; set; }
        public virtual tbUsuarios fact_UserModificacionNavigation { get; set; }
        public virtual tbMetodosPagos meto { get; set; }
        public virtual tbSucursales sucu { get; set; }
        public virtual ICollection<tbFacturaDetalles> tbFacturaDetalles { get; set; }
    }
}