// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Jafouan.Entities.Entities
{
    public partial class tbFardosProveedor
    {
        public int fapr_Id { get; set; }
        public int fard_Id { get; set; }
        public int prov_Id { get; set; }
        public int fapr_Cantidad { get; set; }
        public int? fapr_UserCrea { get; set; }
        public DateTime? fapr_FechaCreacion { get; set; }
        public int? fapr_UserModificacion { get; set; }
        public DateTime? fapr_FechaModificacion { get; set; }
        public bool? fapr_Estado { get; set; }

        public virtual tbUsuarios fapr_UserCreaNavigation { get; set; }
        public virtual tbUsuarios fapr_UserModificacionNavigation { get; set; }
        public virtual tbFardos fard { get; set; }
        public virtual tbProveedores prov { get; set; }
    }
}