// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Jafouan.Entities.Entities
{
    public partial class tbFardos
    {
        public tbFardos()
        {
            tbFardosProveedor = new HashSet<tbFardosProveedor>();
            tbPrendas = new HashSet<tbPrendas>();
        }

        public int fard_Id { get; set; }
        public string fard_Descripcion { get; set; }
        public int? fard_UserCrea { get; set; }
        public DateTime? fard_FechaCreacion { get; set; }
        public int? fard_UserModificacion { get; set; }
        public DateTime? fard_FechaModificacion { get; set; }
        public bool? fard_Estado { get; set; }

        public virtual tbUsuarios fard_UserCreaNavigation { get; set; }
        public virtual tbUsuarios fard_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbFardosProveedor> tbFardosProveedor { get; set; }
        public virtual ICollection<tbPrendas> tbPrendas { get; set; }
    }
}