// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Jafouan.Entities.Entities
{
    public partial class tbMarcas
    {
        public tbMarcas()
        {
            tbPrendas = new HashSet<tbPrendas>();
        }

        public int marc_Id { get; set; }
        public string marc_Descripcion { get; set; }
        public int marc_UserCrea { get; set; }
        public DateTime marc_FechaCrea { get; set; }
        public int? marc_UserModifica { get; set; }
        public DateTime? marc_FechaModificacion { get; set; }
        public bool? marc_Estado { get; set; }

        public virtual tbUsuarios marc_UserCreaNavigation { get; set; }
        public virtual tbUsuarios marc_UserModificaNavigation { get; set; }
        public virtual ICollection<tbPrendas> tbPrendas { get; set; }
    }
}