// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Jafouan.Entities.Entities
{
    public partial class tbPantallas
    {
        public tbPantallas()
        {
            tbPantallasPorRol = new HashSet<tbPantallasPorRol>();
        }

        public int pant_Id { get; set; }
        public string pant_Nombre { get; set; }
        public string pant_Identificador { get; set; }
        public string pant_href { get; set; }
        public bool? pant_Estado { get; set; }
        public int pant_UserCrea { get; set; }
        public DateTime? pant_FechaCrea { get; set; }
        public int? pant_UserModifica { get; set; }
        public DateTime? pant_FechaModifica { get; set; }

        public virtual tbUsuarios pant_UserCreaNavigation { get; set; }
        public virtual tbUsuarios pant_UserModificaNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRol> tbPantallasPorRol { get; set; }
    }
}