// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Jafouan.Entities.Entities
{
    public partial class tbPrendas
    {
        public tbPrendas()
        {
            tbFacturaDetalles = new HashSet<tbFacturaDetalles>();
        }

        public int pren_Id { get; set; }
        public string pren_Descripcion { get; set; }
        public string pren_Talla { get; set; }
        public int desc_Id { get; set; }
        public decimal pren_Precio { get; set; }
        public int marc_Id { get; set; }
        public int cate_Id { get; set; }
        public int fard_Id { get; set; }
        public string pren_Imagen { get; set; }
        public bool? prend_EstadoTienda { get; set; }
        public int? pren_UserCrea { get; set; }
        public DateTime? pren_FechaCreacion { get; set; }
        public int? pren_UserModificacion { get; set; }
        public DateTime? pren_FechaModificacion { get; set; }
        public bool? pren_Estado { get; set; }

        public virtual tbCategorias cate { get; set; }
        public virtual tbDescuentos desc { get; set; }
        public virtual tbFardos fard { get; set; }
        public virtual tbMarcas marc { get; set; }
        public virtual tbUsuarios pren_UserCreaNavigation { get; set; }
        public virtual tbUsuarios pren_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturaDetalles> tbFacturaDetalles { get; set; }
    }
}