// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Jafouan.Entities.Entities
{
    public partial class tbUsuarios
    {
        public int user_Id { get; set; }
        public string user_NombreUsuario { get; set; }
        public int empl_Id { get; set; }
        public string user_Contraseña { get; set; }
        public bool user_Admin { get; set; }
        public int? role_Id { get; set; }
        public bool? user_Estado { get; set; }
        public int user_UserCrea { get; set; }
        public DateTime? user_FechaCrea { get; set; }
        public int? user_UserModifica { get; set; }
        public DateTime? user_FechaModifica { get; set; }
    }
}