// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Jafouan.Entities.Entities
{
    public partial class VW_Departamentos
    {
        public string dept_Id { get; set; }
        public string dept_Descripcion { get; set; }
        public bool? dept_Estado { get; set; }
        public int dept_UserCrea { get; set; }
        public string empl_crea { get; set; }
        public DateTime? dept_FechaCrea { get; set; }
        public int? dept_UserModifica { get; set; }
        public string empl_Modifica { get; set; }
        public DateTime? dept_FechaModifica { get; set; }
    }
}