// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Jafouan.Entities.Entities
{
    public partial class VW_Reporte
    {
        public string Fecha { get; set; }
        public string Total_Ventas_Al_Dia { get; set; }
        public string Total_Dia { get; set; }
    }
}